config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :users
  root "pages#home"
  resources :users, only: [:show]
  resources :collections, :words
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
    has_many :words, dependent: :destroy
    mount_uploader :image, ImageUploader
end

app/models/sound.rb
class Sound < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :words
  has_many :collections
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/word.rb
class Word < ApplicationRecord
    belongs_to :collection
    belongs_to :user
    mount_uploader :image, ImageUploader
    mount_uploader :audio, AudioUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :image, :audio])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :image, :audio])
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def index
    @collections = Collection.all
  end

  def show
    @collection = Collection.find_by(id: params[:id])
    @word = Word.find_by(id: params[:id])
  end

  def new
    @collection = Collection.new
  end

  def create
    collection = current_user.collections.create(collection_params)
    redirect_to collections_path 
  end

  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy

    redirect_to collections_path 
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find_by(id: params[:id])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  skip_before_action :verify_authenticity_token

  def index
    @words = Word.all
  end

  def show
    @word = Word.find_by(id: params[:id])
  end

  def new
    @word = Word.new
  end

  def create
    word = current_user.words.create(word_params)
    # byebug
    respond_to do |f|
      f.html { redirect_to word_path(word) }
      f.json { render json: word }
    end
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to collections_path
  end

  private

  def word_params
    params.require(:word).permit(:term, :arabic_form, :english_form, :example, :collection_id, :audio, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/word_helper.rb
module WordHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/collections/index.html.erb
<div class="container">
<div class="thing">
<div class="card-columns">

<% @collections.each do |t| %>
<div class="card text-center">
 <% if t.image %>
        <%= cl_image_tag t.image, {:class=>"card-img-top"}%>
    <% end %>
    <div class="card-deck">

<div class="col"><h5 style="padding: 10px;"> <%= link_to(t.name, collection_path(t)) %></h5>

</div>
</div>
</div>
 <% end %>
</div>
</div>
</div>


</div>

app/views/collections/new.html.erb
<div class="container">
<div class="collection-new">

<%= form_for @collection do |form| %>
<div class="card" style="padding: 20px;">
<div>
    <strong >Add a New Collection </strong><br>
    <%= form.text_field :name, :required => true %>
  </div>
<br>
  <div>
  <%= form.label "Image" %>
  <%= form.file_field :image, :required => true %>
</div>
<br>
    <div class="actions">
<%= form.submit "Add"%>
</div>
<% end %>
</div>
</div>
</div>

app/views/collections/show.html.erb
<div class="container">
<div class="collection-show">
<h3 style="padding-top: 15px; padding-left: 15px;
">
<%= @collection.name %>
</h3>

<hr>
<br><br>
<p>Choose the word that you want to learn</p>
<% @collection.words.each do |f| %>
<h5>
<div class="card" style="padding: 10px;">
<%= link_to "#{f.term} - #{f.english_form}", f %></h5>
<% end %>
<br><br><br>
<hr>
<button class="btn btn-outline-danger"><%= link_to 'Add a Word', new_word_path %></button> <br><br>

<% if user_signed_in? && @collection.user_id == current_user.id %>
                          <button class="btn btn-outline-danger"><%= link_to 'Delete the Collection', collection_path,
                          method: :delete,
                       data: { confirm: 'Are you sure?' } %></button>
                      <%end %>

</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArabicLearningApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Ovo" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </head>
  <body>
  <header>
      <%= render partial: 'pages/nav' %>
    </header>
    <div class="content">
  <main>
        <%= yield %>
    </main>
    
    <%= render partial: 'pages/footer' %>
   
    </div>
    <script src="main.js"></script>
  </body>
</html>

app/views/pages/_footer.html.erb
 <footer>
 <div class="container">

<p style="text-align: right; color: white; ">2018 Haya AlMousa</p>
</div>
</footer>

app/views/pages/_nav.html.erb
 
 <nav class="navbar navbar-custom navbar-expand-lg" style="background-color: #dc6767;">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    
      <li class="nav-item active">
      
      <%= link_to 'Learn Arabic', root_path, {:class=>"nav-link"} %> 
      </li>

 <% if current_user %>
      <li class="nav-item">
      <%= link_to current_user.name, user_path(current_user), {:class=>"nav-link"} %></li> 
      <li class="nav-item nav-link"><%= link_to 'Log Out', destroy_user_session_path, method: :delete,id:"n" %></li>
      <li class="nav-item"><%= link_to 'Collections', collections_path, {:class=>"nav-link"} %></li>

      <% end %>







     

      
    
  </div>
</nav>

app/views/pages/home.html.erb
<div class="haya">
<div class="shadow-lg p-3 mb-5 rounded">
<h3 class="title">Learn Arabic</h3>
<p class="paragraph">Learn Arabic with this application. You can particpate in adding new words and learn from others' words</p>


<div class="buttons">
<button type="button" class="btn btn-outline-danger"><%= link_to 'Sign Up', new_user_registration_path %></button>
<button type="button" class="btn btn-outline-danger"><%= link_to 'Log In', new_user_session_path %></button>
</div>
</div>
<div class="container" style="padding: 20px;">

</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="users-show">
<div class="thing">

<h4>Welcome
<% if user_signed_in? %>
  <%= current_user.name %>
  <% end %>
  ,</h4>
  <br>
<button class="btn btn-outline-danger"><%= link_to 'Add a Collection', new_collection_path %></button><br><br>
<button class="btn btn-outline-danger"><%= link_to 'Add a Word', new_word_path %></button>
  </div>
</div>
</div>

app/views/words/index.html.erb
<h1>Words#index</h1>
<p>Find me in app/views/words/index.html.erb</p>

app/views/words/new.html.erb
<div class="container">
<div class="word-show">
<div class="card big second">

<%= form_for @word do |s| %>
<div class="card-header">

<h3>New Word</h3>
</div>
<br>
<div class="wrap" style="padding: 15px">
<div style="padding-bottom:10px;">
<strong> Term </strong>
   <%= s.text_field :term, :required => true %>
</div>

<div style="padding-bottom:10px;">
<strong> English form </strong>
<%= s.text_field :english_form, :required => true %>
</div>

<div style="padding-bottom:10px;">
<strong> Arabic form </strong>
<%= s.text_field :arabic_form, :required => true %>
</div>

<div style="padding-bottom:10px;">
<strong> Example </strong>
<%= s.text_field :example, :required => true %>
</div>

<!--<div style="padding-bottom:10px;">
  <strong> Pronunciation </strong>
  <%= s.file_field :audio %>
</div>-->

<div>
  <%= s.label "Image" %>
  <%= s.file_field :image, :required => true %>
</div>

<div style="padding-bottom:10px;">
   <strong> <%= s.label :collection_id, "What collection does this word belong to?" %><strong><br>
    <%= s.collection_select :collection_id, Collection.all, :id, :name, required: true %>
  </div>

<div>
<h3 onclick="recordStop()" id="record-stop-button">Record</h3>
</div>

  <!--<div>
  <%= s.submit %>
  </div>-->

<% end %>
</div>
</div>
</div>
</div>

app/views/words/show.html.erb
<div class="container">
<div class="word-show">
<div class="card big">
<div class="card-header">
<h3><%= @word.term %></h3></div>
<div class="wrap" style="padding: 10px">

<% if @word.image %>
<%= cl_image_tag @word.image, {:class=>"card-img-top"}%>
    <% end %>
<h5> English form: <%= @word.english_form %></h5>
<h5> Arabic form: <%= @word.arabic_form %></h5>
<h5> Example: <%= @word.example %></h5>
<!--<h4> collection: <%= @word.collection.name %></h4>-->
<%= audio_tag @word.audio, controls: true %>

<!--<button onclick=“playAudio()” disabled=“” id=“play-audio-button”>Play</button>-->

</div>

<hr>
<div class="wrap" style="padding-left: 18px;">
<% if user_signed_in? && @word.user_id == current_user.id %>
                          <%= link_to 'Delete', word_path,
                          method: :delete,
                       data: { confirm: 'Are you sure?' } %>
                      <%end %>
                      </div>
</div>
</div>
</div>